[package]
name = "dot-manager"
version = "0.1.0"
edition = "2024"

[features]
default = []
pacman = []

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9"
xdg = "3"
